config/routes.rb
Rails.application.routes.draw do
  root "recipes#index"
  resources :recipes, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	
	def index
		# Get recipes from the Recipe Puppy API with the search params
		@recipes = RecipePuppy.new.recipes(params[:search])
		# Render HTML and Ajax Response
		respond_to do |format|
			format.html
			format.js
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipe Finder</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <!-- Navbar -->
    <%= render "shared/navbar" %>
    <!-- Main Content -->
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/recipes/_table.html.erb
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col"></th>
      <th scope="col">Title</th>
      <th scope="col">Ingredients</th>
    </tr>
  </thead>
  <tbody>
   <% @recipes.each do |recipe| %>
    <tr>
      <td><%= image_tag recipe["thumbnail"] %></td>
      <td><%= link_to recipe["title"], recipe["href"], target: "_blank" %></td>
      <td><%= recipe["ingredients"] %></td>
    </tr>
   <% end %>
  </tbody>
</table>

app/views/recipes/index.html.erb
<div id="recipes-table"><%= render "table", collection: @recipes %></div>

app/views/recipes/index.js.erb
$("#recipes-table").html("<%= j render 'table', collection: @recipes %>")

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light"  style="margin-bottom: 70px;">
    <%= link_to root_path, class: "navbar-brand" do %>
  	<%= image_tag "mortar.png", class: "d-inline-block align-top", width: "30", height: "30" %>
    Recipe Finder
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
 
 	<ul class="navbar-nav mr-auto">
    </ul>
    
    <!-- Search form -->
<%= form_tag recipes_path, :method => 'get', class: "form-inline my-2 my-lg-0", :remote => true, id: "recipes_search_form" do %>

    <%= text_field_tag :search, params[:search], class: "form-control mr-sm-2", placeholder: "search", id: "recipes_search_field", autofocus: true %>
    <%= submit_tag "Search", :name => nil, id: "search_button", style: "display: none;" %>

<% end %>

  </div>
</nav>